# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gust < Formula
  desc "A multi-paned TUI for Zephyr RTOS development with west"
  homepage "https://github.com/buckleypaul/gust"
  version "0.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/buckleypaul/gust/releases/download/v0.0.4/gust_0.0.4_darwin_amd64.tar.gz"
      sha256 "e3ba1ea76074a9f0abac389a77c7dacc047a864ade9701a0d960c7c90ef195ab"

      def install
        bin.install "gust"
      end
    end
    on_arm do
      url "https://github.com/buckleypaul/gust/releases/download/v0.0.4/gust_0.0.4_darwin_arm64.tar.gz"
      sha256 "9d78486bce7230e91c81d0b699d23960b08b27614495ee728045b7a96b4200eb"

      def install
        bin.install "gust"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buckleypaul/gust/releases/download/v0.0.4/gust_0.0.4_linux_amd64.tar.gz"
        sha256 "5fd202a278c6ecac732a63bf27164e9457d6fff15853c92e3a9e52fdaba383a1"

        def install
          bin.install "gust"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buckleypaul/gust/releases/download/v0.0.4/gust_0.0.4_linux_arm64.tar.gz"
        sha256 "c8129d4f85e8efefbbd484c514746a564c251bccc2be55c1feaed6fd81fb31cd"

        def install
          bin.install "gust"
        end
      end
    end
  end
end
