# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Haide < Formula
  desc "AI File Exclusion Manager for Git"
  homepage "https://github.com/buckleypaul/haide"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/buckleypaul/haide/releases/download/v0.2.0/haide_0.2.0_darwin_amd64.tar.gz"
      sha256 "835b480543080e377586b9426bf9bafbc39e400a5ea5e6fb13aa78e9f4a16f28"

      def install
        bin.install "haide"
      end
    end
    on_arm do
      url "https://github.com/buckleypaul/haide/releases/download/v0.2.0/haide_0.2.0_darwin_arm64.tar.gz"
      sha256 "f4226df899df7e1e65a194748d6decb6783e3bc6a46c20d1c4706afcb9690f6b"

      def install
        bin.install "haide"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buckleypaul/haide/releases/download/v0.2.0/haide_0.2.0_linux_amd64.tar.gz"
        sha256 "f310b4ba045b434f6333cf999d69608cae7a5580004d32a0759eb00d7e42b938"

        def install
          bin.install "haide"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buckleypaul/haide/releases/download/v0.2.0/haide_0.2.0_linux_arm64.tar.gz"
        sha256 "a657fa987d5b3a8ff6c54bb58981cb5d82c0bf07aee1f87bb414aeab3ee1ccdd"

        def install
          bin.install "haide"
        end
      end
    end
  end

  test do
    system "#{bin}/haide", "--help"
  end
end
