# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giki < Formula
  desc "Turn any git repository into a browsable wiki"
  homepage "https://github.com/buckleypaul/giki"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buckleypaul/giki/releases/download/v0.2.0/giki_Darwin_x86_64.tar.gz"
      sha256 "02cadb9900eaf508dd2c2dcf1fa8bcd875b6b45aba22c57ccfed5127be748c2f"

      def install
        bin.install "giki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buckleypaul/giki/releases/download/v0.2.0/giki_Darwin_arm64.tar.gz"
      sha256 "12f056b4219951478a4455af5924f9b6dbeb36549dcc583e1a75cc7ea5ca61f3"

      def install
        bin.install "giki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buckleypaul/giki/releases/download/v0.2.0/giki_Linux_x86_64.tar.gz"
      sha256 "56e2b484b1000715c70d6abe3a2f2e947487d5f4bd52b1e14ec03a05de4306b5"
      def install
        bin.install "giki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buckleypaul/giki/releases/download/v0.2.0/giki_Linux_arm64.tar.gz"
      sha256 "450404f4aff846acafd8eb48e91ee588238504271fe37f06aa990cd0bf63972b"
      def install
        bin.install "giki"
      end
    end
  end

  test do
    system "#{bin}/giki version"
  end
end
