# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giki < Formula
  desc "Turn any git repository into a browsable wiki"
  homepage "https://github.com/buckleypaul/giki"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buckleypaul/giki/releases/download/v0.2.0/giki_Darwin_x86_64.tar.gz"
      sha256 "38e5a6cb86ec056f51925312434e0997a7ccc67b0a868013a485537bd4912141"

      def install
        bin.install "giki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buckleypaul/giki/releases/download/v0.2.0/giki_Darwin_arm64.tar.gz"
      sha256 "22f63780053430d95ea4bd9b4411efec517149d6ba51ad46a10e3728348514e2"

      def install
        bin.install "giki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buckleypaul/giki/releases/download/v0.2.0/giki_Linux_x86_64.tar.gz"
      sha256 "d29f9a74e6e10bb8249f962eb3b75241545888656558f0b15ec1f35022b04c04"
      def install
        bin.install "giki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buckleypaul/giki/releases/download/v0.2.0/giki_Linux_arm64.tar.gz"
      sha256 "2f04d0cd1443b2bef9a2af88256375a5577ca5b6723c86eb8822e449b02ec25e"
      def install
        bin.install "giki"
      end
    end
  end

  test do
    system "#{bin}/giki version"
  end
end
