# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Haide < Formula
  desc "AI File Exclusion Manager for Git"
  homepage "https://github.com/buckleypaul/haide"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/buckleypaul/haide/releases/download/v0.3.0/haide_0.3.0_darwin_amd64.tar.gz"
      sha256 "e9cf06b8bc1092a0b4dca44afaa47999fdc0da2ce4dbd4f5fba3a214ec796495"

      def install
        bin.install "haide"
      end
    end
    on_arm do
      url "https://github.com/buckleypaul/haide/releases/download/v0.3.0/haide_0.3.0_darwin_arm64.tar.gz"
      sha256 "d8813ad96eca095803ac515326a202e5713ea02048cbf5385be2b1a75492767e"

      def install
        bin.install "haide"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buckleypaul/haide/releases/download/v0.3.0/haide_0.3.0_linux_amd64.tar.gz"
        sha256 "aa249f37e7f38c49ebbef67a181fe5214754439c4c2c262fc52b74ac021abe70"

        def install
          bin.install "haide"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buckleypaul/haide/releases/download/v0.3.0/haide_0.3.0_linux_arm64.tar.gz"
        sha256 "d0e7f5068e403f05c5a1fcaa2923e0fedf4a8bd44ea703d9dcba3bcffa974a8d"

        def install
          bin.install "haide"
        end
      end
    end
  end

  test do
    system "#{bin}/haide", "--help"
  end
end
