# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Haide < Formula
  desc "AI File Exclusion Manager for Git"
  homepage "https://github.com/buckleypaul/haide"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/buckleypaul/haide/releases/download/v0.2.0/haide_0.2.0_darwin_amd64.tar.gz"
      sha256 "00ee3d4dc6dc42b964635f2eac7b0fa4839727ac220451b0a2e85edd5de810ca"

      def install
        bin.install "haide"
      end
    end
    on_arm do
      url "https://github.com/buckleypaul/haide/releases/download/v0.2.0/haide_0.2.0_darwin_arm64.tar.gz"
      sha256 "b0dca6983bf866a5d17e0b7183956dfb56a8a3ac380cfc3ed1525e18987954f8"

      def install
        bin.install "haide"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buckleypaul/haide/releases/download/v0.2.0/haide_0.2.0_linux_amd64.tar.gz"
        sha256 "e3e5fa8bedd74ec9e41ad126464faf6452991235e610f5f8433874a10eb62cf0"

        def install
          bin.install "haide"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buckleypaul/haide/releases/download/v0.2.0/haide_0.2.0_linux_arm64.tar.gz"
        sha256 "eecec37edc0d82ddabc786da91dacfcb711c55424994cbb72d7319776ef260e0"

        def install
          bin.install "haide"
        end
      end
    end
  end

  test do
    system "#{bin}/haide", "--help"
  end
end
