# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdmu < Formula
  desc "Terminal UI tool for annotating markdown files with line-level comments"
  homepage "https://github.com/buckleypaul/mdmu"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buckleypaul/mdmu/releases/download/v0.1.0/mdmu_Darwin_x86_64.tar.gz"
      sha256 "0d4088fec840f44b9a8c7e3f1557cd00b2d3e27a8a4a146d5f29572b5a961b72"

      def install
        bin.install "mdmu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buckleypaul/mdmu/releases/download/v0.1.0/mdmu_Darwin_arm64.tar.gz"
      sha256 "2bc857ce29a6b6b03045e82063f9bab9ddeb225f298708dfc83e9f39b8a834d7"

      def install
        bin.install "mdmu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buckleypaul/mdmu/releases/download/v0.1.0/mdmu_Linux_x86_64.tar.gz"
      sha256 "bfae943a153056d483f38c2f3d2c59c42a5d827f14fc427fc7ae42fa65cdf006"
      def install
        bin.install "mdmu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buckleypaul/mdmu/releases/download/v0.1.0/mdmu_Linux_arm64.tar.gz"
      sha256 "50dd5049206e92ecaf327ca842415002205e8f95105b3705258c408a3a7a9751"
      def install
        bin.install "mdmu"
      end
    end
  end

  test do
    system "#{bin}/mdmu", "--version"
  end
end
